Feature/add to queue
Crow08/YTBSP pull request #62
Opened 2020-11-21 23:50 UTC by xHawkyx

pls be gentle...

2020-11-23 14:23 UTC, Crow08 requested changes

2020-11-23 14:23 UTC, Crow08 commented on src/Components/SubListComponent.ts
> +            alert("Queue is empty, you need to add videos first, duh!");
do you even add bro!

2020-11-23 14:23 UTC, Crow08 commented on src/Components/VideoComponent.ts
> +import { isPropertyName } from "typescript";
unused import

2020-11-23 14:23 UTC, Crow08 commented on src/Components/VideoComponent.ts
> +        this.addToQueueItem = $("<p/>", {
can also be a span instead of p

2020-11-23 14:23 UTC, Crow08 commented on src/Components/VideoComponent.ts
> +        this.addToQueueItem.mouseover(() => this.abortEnlargeTimeout());
this change is not needed anymore.

2020-11-23 14:23 UTC, Crow08 commented on src/Components/VideoComponent.ts
> +        this.clipItem.add(this.titleItem).add(this.addToQueueItem).click((event) => this.handleOpenVideo(event));
this change is not needed anymore.

2020-11-25 09:03 UTC, xHawkyx commented on src/Components/VideoComponent.ts
> +import { isPropertyName } from "typescript";
removed useless import

2020-11-25 09:03 UTC, xHawkyx commented on src/Components/SubListComponent.ts
> +            alert("Queue is empty, you need to add videos first, duh!");
added rickroll, changed alert a bit

2020-11-25 09:04 UTC, xHawkyx commented on src/Components/VideoComponent.ts
> +        this.addToQueueItem = $("<p/>", {
changed to <span>

2020-11-25 19:19 UTC, xHawkyx commented on src/Components/VideoComponent.ts
> +        if ((event.target as Element).classList.contains(this.closeItem.attr("class")) || (event.target as Element).classList.contains(this.addToQueueItem.attr("class"))) {
removed useless code

2020-11-25 19:20 UTC, xHawkyx commented on src/Components/VideoComponent.ts
> +        this.addToQueueItem.mouseover(() => this.abortEnlargeTimeout());
removed shamefull code

2020-11-25 19:20 UTC, xHawkyx commented on src/Components/VideoComponent.ts
> +        this.clipItem.add(this.titleItem).add(this.addToQueueItem).click((event) => this.handleOpenVideo(event));
removed preposterous line of code

2020-11-25 19:25 UTC, Crow08 approved these changes

2020-11-25 19:25 UTC, merged